# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Wonung Kim
title: Graduate Student of School of Computing, KAIST
email: wukim@casys.kaist.ac.kr
phone: +82 10-6326-5969
website: https://waneon.me

# Additional icon links
additional_links:
- title: CV Download
  icon: far fa-file-pdf
# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  waneon

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: resources/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Graduate student in School of Computing in KAIST. I'm advised by [Prof. Jongse Park.](https://jongse-park.github.io/)  

  Address: 291 Daehak-ro, Yuseong-gu, E3-1 #4414, Daejeon, 34141, South Korea

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: KAIST
        sub_title: M.S. in School of Computing
        caption: 2023.09 ~
        quote: >
          Korea Advanced Institute of Science and Technolog
        description: | # this will include new lines to allow paragraphs
          * Advisor: Prof. Jongse Park
      - layout: left
        title: Korea University
        sub_title: B.S. in Computer Science and Engineering
        caption: 2020.03 ~ 2023.09
        # quote: >
        #   291 Daehak-ro, Yuseong-gu, E3-1 #4414, Daejeon, 34141, South Korea
        description: | # this will include new lines to allow paragraphs
          * Cumulative GPA: 4.28
          * Major GPA: 4.38

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
