version: '3'

services:
  jekyll:
    image: jekyll/jekyll:3.8
    container_name: homepage
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 8002:4000
    volumes:
      - ./:/srv/jekyll
    environment:
      - PUID=1026
      - PGID=100
